osx_image: xcode12.2
language: swift

jobs:
  include:
    - stage: Test, Generate Coverage
      install:
        - brew update
        - brew outdated cocoapods || brew upgrade cocoapods
        - brew install xcodegen
      script:
        - set -o pipefail && xcodebuild -workspace Minerva.xcworkspace -scheme MinervaExample -destination 'platform=iOS Simulator,name=iPhone 12 Pro Max,OS=14.2' build | xcpretty
